### ISSUE TITLE
top?

### ISSUE THREAD

**Issue by markito12** [MonsterMannen/fortnitetracker-7days-stats#7]
how does the tops work, cause i want to use single 3, 5 etc

**Comment by MonsterMannen** [comment]
I'm not sure why they are named `3_5_10` on fortnitetracker. Weird stat. I'll ask them and comment again if I get a reply :smiley: 

I've added methods to get stats for solo, duo and squad if that is what you wanted with your "single" request.

```
fnt.getStatsSolo("markito12", "pc", (err, result) => {
        // do stuff
});
```

**Comment by markito12** [comment]
Thank you so much!! I meant, get the top 5 or 3 or 2 individually. Im working on a complex discord bot for a huge tournament here in Argentina so i need it to be accured if u could give me a hand with that it would be awesome!!

**Comment by markito12** [comment]
Another question is, any way to get currrnt match data?

**Comment by MonsterMannen** [comment]
>get the top 5 or 3 or 2 individually

That data doesn't exist on fortnitetracker.com so no, nothing I can do.


>any way to get currrnt match data

Haven't looked it up but it isn't what this module is for so won't add it. Not sure if it even exists.

**Comment by markito12** [comment]
ok thanks
