### ISSUE TITLE
json parse issue

### ISSUE THREAD

**Issue by markito12** [MonsterMannen/fortnitetracker-7days-stats#8]
1|mod  | SyntaxError: Unexpected token l in JSON at position 0
1|mod  |     at JSON.parse (<anonymous>)
1|mod  |     at Request.request [as _callback] (/home/laster/Node/node_modules/fortnitetracker-7days-stats/index.js:43:29)
1|mod  |     at Request.self.callback (/home/laster/Node/node_modules/request/request.js:185:22)
1|mod  |     at emitTwo (events.js:126:13)
1|mod  |     at Request.emit (events.js:214:7)
1|mod  |     at Request.<anonymous> (/home/laster/Node/node_modules/request/request.js:1161:10)
1|mod  |     at emitOne (events.js:116:13)
1|mod  |     at Request.emit (events.js:211:7)
1|mod  |     at IncomingMessage.<anonymous> (/home/laster/Node/node_modules/request/request.js:1083:12)
1|mod  |     at Object.onceWrapper (events.js:313:30)

**Comment by markito12** [comment]
when using !verify Ranger on wiifit stream pro, i get "Ranger on wiifit" if its an existant user errors, if not  "Player not found" line: var jsonStats = JSON.parse(last7);

**Comment by MonsterMannen** [comment]
Seems like fortnitetracker made som changes to their site. I try fix it. Maybe now, maybe tomorrow.

**Comment by MonsterMannen** [comment]
Now working again.
Update the package to latest (3.3.1)

I'm not playing fortnite anymore so I'm not sure what these new stats are. fortnitetracker says they have V2 stats that are the same as ingame stats but you can't specify a platform for them.. so are all playernames unique across all platforms?  Works for PC atleast.

**Comment by markito12** [comment]
Awesome! pretty sure they added trio stats. thanks again!
